# Generated by Django 5.1.7 on 2025-05-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_p', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('free', 'Free Services'), ('one_time', 'One Time Fee/Hybrid')], default='free', max_length=20),
        ),
    ]
