# Generated by Django 5.1.7 on 2025-05-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_p', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('free', 'Free Services'), ('one_time', 'One Time Fee/Hybrid'), ('subscription', 'Subscription')], default='free', max_length=20),
        ),
    ]
